## production d'un DF de tous les noeuds de HACKMD traitalbe en tant qu'attribut dans R

In [3]:
import pandas as pd 
import numpy as np

In [2]:
##Constitution des listes d'id:

In [4]:
df = pd.read_csv("2com_climat_100.csv")
com_climat1 = df["0"]
com_climat2 = df["2"]


l_ex_cs = [88696744,
841847597081882625,
306577270,
1090472228741939200,
23023227,
1032904812281520128,]

l_top_cs = [40316065,
16434993,
1202197705973469184,
757300766478663680,
1172345379125260288,
894381348,
883467071727616000,
2659475605,
1200326345680539649,
25235151,
933894571511001088]

l_other = [18643437,
1392956425,
348113898,
2725865306,
2663797417,
1122955143765479433,
25805685]


l_pc = [1892683062,
420100653,
16094885,
384923143,
198296897,
1006419421244678144,
956250134786002944,
611278121,
425580734,
25960714,
15088481,
3141635426,
495650403,
602403521,
748523910,
2490890594, 
1897328731,
1582824926,
919008127793500160,
750959971]

In [17]:
### automatisation en cours 

col = []

####create the df 
pd.DataFrame(col)
for element in [com_climat1,com_climat2] :
    for id in element :

Empty DataFrame
Columns: []
Index: []

In [20]:
dict1 = {"Id": com_climat1,"COM1":np.ones(100),"COM2":np.zeros(100)}
dict2 = {"Id": com_climat2, "COM1":np.ones(100),"COM2":np.ones(100)}
df1, df2= pd.DataFrame(dict1),  pd.DataFrame(dict2)

In [21]:
df_main_communities = pd.concat([df1, df2])
df_main_communities.to_csv("main_communities.csv")

# On ajoute aux edges des attributs

In [18]:
df_pc = pd.read_csv("multilayer_pc.csv")
df_pc.head()



j = df_pc[df_pc.date==0o2]
f = df_pc[df_pc.date==0o3]
m = df_pc[df_pc.date==0o4]
a = df_pc[df_pc.date==0o5]
ma = df_pc[df_pc.date==0o6]
ju = df_pc[df_pc.date==0o7]

TypeError: list indices must be integers or slices, not str

,date,target,source,jan,ma,av,m,ju,fev,mar,avr,mai,jui
9120,2,3141635426,16832632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9121,2,3141635426,22573600,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9122,2,3141635426,45291573,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9123,2,495650403,611278121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9124,2,3141635426,2670830970,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
j["jan"]= np.zeros(len(j["target"]))
j["fev"]=np.ones(len(j["target"]))
j["ma"]=np.zeros(len(j["target"]))
j["av"]=np.zeros(len(j["target"]))
j["m"]=np.zeros(len(j["target"]))
j["ju"]=np.zeros(len(j["target"]))

f["jan"]= np.zeros(len(f["target"]))
f["fev"]=np.ones(len(f["target"]))
f["ma"]=np.zeros(len(f["target"]))
f["av"]=np.zeros(len(f["target"]))
f["m"]=np.zeros(len(f["target"]))
f["ju"]=np.zeros(len(f["target"]))

m["jan"]= np.zeros(len(m["target"]))
m["fev"]=np.zeros(len(m["target"]))
m["ma"]=np.ones(len(m["target"]))
m["av"]=np.zeros(len(m["target"]))
m["m"]=np.zeros(len(m["target"]))
m["ju"]=np.zeros(len(m["target"]))


a["jan"]= np.zeros(len(a["target"]))
a["fev"]=np.zeros(len(a["target"]))
a["ma"]=np.zeros(len(a["target"]))
a["av"]=np.ones(len(a["target"]))
a["m"]=np.zeros(len(a["target"]))
a["ju"]=np.zeros(len(a["target"]))

ma["jan"]= np.zeros(len(ma["target"]))
ma["fev"]=np.zeros(len(ma["target"]))
ma["ma"]=np.zeros(len(ma["target"]))
ma["av"]=np.zeros(len(ma["target"]))
ma["m"]=np.ones(len(ma["target"]))
ma["ju"]=np.zeros(len(ma["target"]))

ju["jan"]= np.zeros(len(ju["target"]))
ju["fev"]=np.zeros(len(ju["target"]))
ju["ma"]=np.zeros(len(ju["target"]))
ju["av"]=np.zeros(len(ju["target"]))
ju["m"]=np.zeros(len(ju["target"]))
ju["ju"]=np.ones(len(ju["target"]))

<ipython-input-19-7c7365defb1d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j["jan"]= np.zeros(len(j["target"]))
<ipython-input-19-7c7365defb1d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j["fev"]=np.ones(len(j["target"]))
<ipython-input-19-7c7365defb1d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j["ma"]=np.zeros(len(j["target"]))
<ipython-input-19-7c7365defb1d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j["av"]=np.zeros(len(j["target"]))
<ipython-input-19-7c7365defb1d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j["m"]=np.zeros(len(j["target"]))
<ipython-input-19-7c7365defb1d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  j["ju"]=np.zeros(len(j["target"]))
<ipython-input-19-7c7365defb1d>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f["jan"]= np.zeros(len(f["target"]))
<ipython-input-19-7c7365defb1d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f["fev"]=np.ones(len(f["target"]))
<ipython-input-19-7c7365defb1d>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f["ma"]=np.zeros(len(f["target"]))
<ipython-input-19-7c7365defb1d>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f["av"]=np.zeros(len(f["target"]))
<ipython-input-19-7c7365defb1d>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f["m"]=np.zeros(len(f["target"]))
<ipython-input-19-7c7365defb1d>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f["ju"]=np.zeros(len(f["target"]))
<ipython-input-19-7c7365defb1d>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m["jan"]= np.zeros(len(m["target"]))
<ipython-input-19-7c7365defb1d>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m["fev"]=np.zeros(len(m["target"]))
<ipython-input-19-7c7365defb1d>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m["ma"]=np.ones(len(m["target"]))
<ipython-input-19-7c7365defb1d>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m["av"]=np.zeros(len(m["target"]))
<ipython-input-19-7c7365defb1d>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m["m"]=np.zeros(len(m["target"]))
<ipython-input-19-7c7365defb1d>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m["ju"]=np.zeros(len(m["target"]))
<ipython-input-19-7c7365defb1d>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["jan"]= np.zeros(len(a["target"]))
<ipython-input-19-7c7365defb1d>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["fev"]=np.zeros(len(a["target"]))
<ipython-input-19-7c7365defb1d>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["ma"]=np.zeros(len(a["target"]))
<ipython-input-19-7c7365defb1d>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["av"]=np.ones(len(a["target"]))
<ipython-input-19-7c7365defb1d>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["m"]=np.zeros(len(a["target"]))
<ipython-input-19-7c7365defb1d>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["ju"]=np.zeros(len(a["target"]))
<ipython-input-19-7c7365defb1d>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma["jan"]= np.zeros(len(ma["target"]))
<ipython-input-19-7c7365defb1d>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma["fev"]=np.zeros(len(ma["target"]))
<ipython-input-19-7c7365defb1d>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma["ma"]=np.zeros(len(ma["target"]))
<ipython-input-19-7c7365defb1d>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma["av"]=np.zeros(len(ma["target"]))
<ipython-input-19-7c7365defb1d>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma["m"]=np.ones(len(ma["target"]))
<ipython-input-19-7c7365defb1d>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma["ju"]=np.zeros(len(ma["target"]))
<ipython-input-19-7c7365defb1d>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ju["jan"]= np.zeros(len(ju["target"]))
<ipython-input-19-7c7365defb1d>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ju["fev"]=np.zeros(len(ju["target"]))
<ipython-input-19-7c7365defb1d>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ju["ma"]=np.zeros(len(ju["target"]))
<ipython-input-19-7c7365defb1d>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ju["av"]=np.zeros(len(ju["target"]))
<ipython-input-19-7c7365defb1d>:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ju["m"]=np.zeros(len(ju["target"]))
<ipython-input-19-7c7365defb1d>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ju["ju"]=np.ones(len(ju["target"]))

      date      target      source  jan   ma   av    m   ju
9120     2  3141635426    16832632  1.0  0.0  0.0  0.0  0.0
9121     2  3141635426    22573600  1.0  0.0  0.0  0.0  0.0
9122     2  3141635426    45291573  1.0  0.0  0.0  0.0  0.0
9123     2   495650403   611278121  1.0  0.0  0.0  0.0  0.0
9124     2  3141635426  2670830970  1.0  0.0  0.0  0.0  0.0

In [20]:
df_pro_climat = pd.concat([j,f,m,a,ma,ju])
df_pro_climat.tail()

df_pro_climat.to_csv("pro_climat.csv")

In [33]:
df_pro_climat[df_pro_climat.target==df_pro_climat.source]

#df_pro_climat[df_pro_climat.target== 3141635426]
#df_pro_climat[df_pro_climat.source== 3141635426]

,date,target,source,jan,fev,ma,av,m,ju
9142,2,384923143,384923143,0.0,1.0,0.0,0.0,0.0,0.0
9147,2,384923143,384923143,0.0,1.0,0.0,0.0,0.0,0.0
9150,2,384923143,384923143,0.0,1.0,0.0,0.0,0.0,0.0
9186,2,384923143,384923143,0.0,1.0,0.0,0.0,0.0,0.0
9205,2,956250134786002944,956250134786002944,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
45360,7,384923143,384923143,0.0,0.0,0.0,0.0,0.0,1.0
45365,7,956250134786002944,956250134786002944,0.0,0.0,0.0,0.0,0.0,1.0
45369,7,956250134786002944,956250134786002944,0.0,0.0,0.0,0.0,0.0,1.0
45379,7,495650403,495650403,0.0,0.0,0.0,0.0,0.0,1.0
45385,7,384923143,384923143,0.0,0.0,0.0,0.0,0.0,1.0

In [21]:
###on cherche les relations nouvelles de chaque mois, à commencer par janvier et février

###relations égales ce mois-ci

liste_source = []
liste_target = []

for i in df_pro_climat.target :
    for j in df_pro_climat.source :
         df_proclimat[i==j]

NameError: name 'df_proclimat' is not defined